dbt_training:
  outputs:
    dev:
      account: ep51091.switzerland-north.azure
      database: ANALYTICS_DEV
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_TRAINING_WH
    prod: 
      account: ep51091.switzerland-north.azure
      database: ANALYTICS
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: DBT_TRAINING
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: DBT_TRAINING_WH   
  target: dev
